[package]
name = "mnemonic-signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
bip32 = { version = "0.2.2", features = ["bip39"] }
k256 = { version = "0.9.6", features = ["ecdsa"] }
ripemd160 = "0.9.1"
sha2 = "0.9.8"
sha3 = { version = "0.9.1", optional = true }
solo-machine-core = { path = "../../solo-machine-core" }

[features]
default = []
ethermint = ["sha3", "solo-machine-core/ethermint"]
