[workspace]
members = [
    "solo-machine",
    "solo-machine-core",
    "event-hooks/stdout-logger",
    "signers/mnemonic-signer",
]
resolver = "2"

[profile.release]
lto = true
overflow-checks = true
