[package]
name = "solo-machine"
version = "0.1.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
async-trait = "0.1.51"
bip32 = { version = "0.2.1", features = ["bip39"] }
cli-table = { version = "0.4.6", default-features = false, features = [
    "derive",
] }
dotenv = "0.15.0"
env_logger = "0.9.0"
hex = "0.4.3"
humantime = "2.1.0"
k256 = { version = "0.9.6", features = ["ecdsa"] }
libloading = "0.7.0"
log = "0.4.14"
num-rational = "0.4.0"
prost = "0.7.0"
prost-types = "0.7.0"
rust_decimal = "1.15.0"
serde_json = "1.0.66"
solo-machine-core = { path = "../solo-machine-core", features = [
    "solomachine-v2",
] }
structopt = "0.3.22"
tendermint = "0.21.0"
termcolor = "1.1.2"
tokio = { version = "1.10.1", features = ["fs", "macros", "rt-multi-thread"] }
tonic = { version = "0.4.3", features = ["tls", "tls-roots"] }

[features]
default = []
ethermint = ["solo-machine-core/ethermint"]
postgres = ["solo-machine-core/postgres"]

[build-dependencies]
prost-build = "0.7.0"
tonic-build = "0.4.2"
