[package]
name = "solo-machine-core"
version = "0.1.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
bech32 = "0.8.1"
chrono = "0.4.19"
cosmos-sdk-proto = "0.5.0"
hex = { version="0.4.3", features=["serde"] }
ibc = { path="../ibc" }
k256 = { version="0.9.4", features=["ecdsa", "sha256"], optional=true }
num-rational = { version="0.4.0", features=["serde"] }
prost = "0.7.0"
prost-types = "0.7.0"
ripemd160 = "0.9.1"
rust_decimal = "1.14.3"
serde = { version="1.0.126", features=["derive"] }
serde_json = "1.0.64"
sha2 = "0.9.5"
sqlx = { version="0.5.5", features=[
    "json",
    "macros",
    "runtime-tokio-rustls",
    "sqlite",
    "chrono",
] }
tendermint = "0.20.0"
tendermint-light-client = "0.20.0"
tendermint-rpc = { version="0.20.0", features=["http-client"] }
tiny-bip39 = { version="0.8.0", optional=true }
tiny-hderive = { version="0.3.0", optional=true }
tokio = { version="1.8.0", features=["sync"] }

[features]
default = ["mnemonic-signer"]
mnemonic-signer = ["k256", "tiny-bip39", "tiny-hderive"]
